pool:
  vmImage: 'windows-2019'

steps:
# Use Python version 3.6
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6' 
    addToPath: true 
    architecture: 'x64'
#- script: python --version
- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'
- script: |
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install requirements'

- script: python -m xmlrunner discover tests -o /tmp/build/quickDDM-tests
  displayName: 'Run all tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '/tmp/build/quickDDM-tests'
    testRunTitle: 'Publish test results'
